name: PyInstaller Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Build PyInstaller package
      run: pyinstaller --onefile main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my_script_package
        path: dist/
